server:
  port: 9888

default-logging-service:
  enabled: on
  aspectsProperties:

    - enabled: on
      patterns:
        - execution(* ru.clevertec..*controller*..*(..))
      loggingFormat:
        dateFormat: yyyy-MM-dd HH:mm:ss
        argumentPrints: true
        returnValuePrints: true

    - enabled: on
      patterns:
        - execution(* ru.clevertec..*repository*..*(..))
        - execution(* ru.clevertec..*service*..*(..))
      loggingFormat:
        dateFormat: HH:mm:ss.SSS
        argumentPrints: true
        returnValuePrints: true



